### ISSUE TITLE
Unable to handle export request

### ISSUE THREAD

**Issue by asrafilll** [asrafilll/order-management#14]
Site still unable to handle export request.

Link : 
https://frjames.space/orders?start_date=2023-01-01&end_date=2023-12-31&product_name=CPR&action=export

Image : 
<img width="713" alt="image" src="https://user-images.githubusercontent.com/49506318/225598521-fca48235-133c-4d28-835c-25f2ca26c441.png">

**Comment by msyrl** [comment]
![image](https://user-images.githubusercontent.com/34615565/226090317-384958b0-ee17-4022-b099-24535a0d8745.png)
Closes with extend memory limit.
